### ISSUE TITLE
Build basic iOS Augmented Reality features

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/DreamBuilder#5]
User should be able to:

- Aim camera at a nearby building (or wall)
- See the ground and wall planes "lit up" (highlighted in some way) to confirm that the iPhone sees those planes
- Attach a 3D (USDZ) object to that wall, so that it is connected to both the wall and the ground plane
- Move around in space and see the object from different angles
- The object should be "lit" based on the current lighting in the room (iOS AR feature)

**Comment by tedbarnett** [comment]
Copy any common AR app (or Apple's own demo AR app) for a reference

**Comment by ChiefSeattle** [comment]
Trex (deck builder visualiser).  It recognizes exterior walls and floor planes. 

https://apps.apple.com/app/id1561806489

**Comment by bhautikpatoliya004** [comment]
@tedbarnett @ChiefSeattle 
I pushed code on the DreamBuilder repo.

- Placed 3D object on the AR
- Added gestures like Zoom, move, rotate and also added light control

When you open an app, there are be 3 options for different 3D files.
You can choose any one of them and click on "Place 3D Object"  and the AR view opens on the new screen. You need to move your iPhone camera. When the ground surface area is found, the selected 3D object will automatically placed on the ground.

Now, you can zoom, move, rotate, and also added light control to that object.

Currently, I'm working on finding solutions that find wall and ground surfaces as described in the GitHub issue. But the problem is we can place objects on any one surface either ground or wall. So, I'm trying this.

**Comment by tedbarnett** [comment]
Current alpha demo video at https://drive.google.com/file/d/1Tq-9Fdlk5IjFWpyJMNzLc7XkzXXobO3H/view?usp=drive_link

![image](https://github.com/user-attachments/assets/a078abc3-73e5-4e2b-89da-a7b85c10e5b0)

**Comment by ChiefSeattle** [comment]
Cool!

**Comment by bhautikpatoliya004** [comment]
@tedbarnett @ChiefSeattle I've pushed the latest source code to the DreamBuilder repo, including the following updates:

• Improved gestures such as zoom, drag, rotate, and dynamic lighting.

• Ground planes are now dynamically displayed when moving your iPhone. This allows you to place objects manually by touching the desired spot, rather than having the ground plane added automatically upon detection (as it was previously).

Additionally, I think we no longer need to detect wall planes, as 3D objects can now be moved freely to any position.

Could you please try this? and please let me know your feedback.

**Comment by tedbarnett** [comment]
It's looking awesome, @bhautikpatoliya004 .  I think you're right that we don't need the wall plane at this point.  Eventually we will want walls (e.g. to project realistic shadows onto the wall), but I'll add that as a separate lower-priority issue.

**Comment by ChiefSeattle** [comment]
Feedback

Once the floor plane has been established and the 3d object has been placed, the floor plane overlay should disappear

**Comment by bhautikpatoliya004** [comment]
@ChiefSeattle Currently, there is an option to remove/show overlay on the ground plan using top right menu button. But if you want then I will remove it once object placed.

**Comment by ChiefSeattle** [comment]
I found the menu item for the overlay...fine like that :)

**Comment by ChiefSeattle** [comment]
Using IPAD pro 12.9" 
I've noticed the plane overlay is fixed to the movement of the camera and often appears slightly off center.

Also, when I place the object, I cannot move away from the object to look at it from a distance (the object moves with me).

In order to scale the object to a floor and wall, I need to be able to move away from the surfaces with the camera in order to view the entire object.  I don't seem to be able to do that currently.
